image: ubuntu:latest

before_script:
  - apt-get update
  - DEBIAN_FRONTEND="noninteractive" apt -y install python3 python3-pip
  - pip3 install -r requirements.txt

fetch_limits:
  stage: test
  script:
    - python3 get_dockerhub_limit.py --verbose


